FROM envoyproxy/envoy-dev

COPY ./direct-resp-envoy.yaml /etc/direct-resp-envoy.yaml
RUN chmod go+r /etc/direct-resp-envoy.yaml
CMD ["/usr/local/bin/envoy", "-c", "/etc/direct-resp-envoy.yaml", "--service-cluster", "front-proxy"]
